title: "Smyles1105's lab notes"

baseurl: ""

url: "https://myleswolfe.ca/"

theme: jekyll-theme-midnight
layout: default

markdown: kramdown

author: 
    name: "Smyles1105"
    email: "mylesw6575@gmail.com"