title: "Smyles1105's lab notes"

baseurl: ""

url: "https://myleswolfe.ca/"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

layout: default

markdown: kramdown

author: 
    name: "Smyles1105"
    email: "mylesw6575@gmail.com"